# Generated by Django 5.1.3 on 2024-12-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCommentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'document"."commentary_child',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'document"."commentary',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(null=True)),
                ('type_id', models.CharField(blank=True, max_length=90, null=True, unique=True)),
                ('common_identifier', models.UUIDField(blank=True, default=None, null=True)),
                ('viewed_times', models.IntegerField(default=0)),
                ('is_moderated', models.BooleanField(default=True)),
                ('is_ready_for_publish', models.BooleanField(default=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'document"."documents',
                'ordering': ['id'],
            },
        ),
    ]
