# Generated by Django 5.1.4 on 2024-12-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='document.document')),
            ],
            options={
                'db_table': 'fc_department',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.department')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='document.document')),
            ],
            options={
                'db_table': 'fc_direction',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('middle_name', models.CharField(max_length=70)),
                ('text', models.TextField()),
                ('direction', models.ManyToManyField(db_table='fc_lecturer_direction', to='structure.direction')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='document.document')),
            ],
            options={
                'db_table': 'fc_lecturer',
            },
        ),
    ]
