# Generated by Django 5.1.3 on 2024-12-22 20:22

import core.direct_sql_worker.server_time
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('is_ipv6', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True, default='not_presented', null=True)),
                ('operation_system', models.CharField(default='not_presented', max_length=100)),
                ('browser_name', models.CharField(blank=True, default='not_presented', max_length=100, null=True)),
                ('request_dt', models.DateTimeField(default=core.direct_sql_worker.server_time.get_server_time_now)),
                ('code_email', models.TextField(blank=True, default=None, null=True, verbose_name='Токен для подтверждения')),
                ('code_email_valid_to_dt', models.DateTimeField(blank=True, null=True, verbose_name='Действителен до')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user"."registration_information',
            },
        ),
        migrations.CreateModel(
            name='UserRequestLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('is_ipv6', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True, default='not_presented', null=True)),
                ('operation_system', models.CharField(default='not_presented', max_length=100)),
                ('browser_name', models.CharField(blank=True, default='not_presented', max_length=100, null=True)),
                ('request_dt', models.DateTimeField(default=core.direct_sql_worker.server_time.get_server_time_now)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user"."request_logs',
            },
        ),
    ]
