# Generated by Django 5.1.3 on 2024-12-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_registrationinformation_userrequestlogger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationinformation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userlogininformation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userrequestlogger',
            old_name='user_id',
            new_name='user',
        ),
    ]
