# Generated by Django 5.1.4 on 2024-12-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='document.document')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=300)),
                ('text_markup', models.TextField()),
                ('fork_start', models.FloatField(blank=True, null=True)),
                ('fork_end', models.FloatField(blank=True, null=True)),
                ('currency_type', models.CharField(default='руб.', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_set', to='work.company')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='document.document')),
            ],
        ),
    ]
